### ISSUE TITLE
Catalog editing?

### ISSUE THREAD

**Issue by Pokeclipse** [marcrobledo/acnl-editor#12]
Hey there,

Just wanted to say thank you and great job on the editor. I was just wondering if you plan to implement editing of the Nookling catalog (or at least the ability to instantly fill it in with every possible entry). Would be a handy feature. Either way, the editor is fantastic and I in no way mean to come off as ungrateful or entitled. Just curious if this feature is in the pipeline for a possible future update.

**Comment by marcrobledo** [comment]
It's definitively possible. But no one has documented it sadly, and I have no time to look at it now :-(

**Comment by marcrobledo** [comment]
This should be working now!
