### ISSUE TITLE
Japanese language support

### ISSUE THREAD

**Issue by mirukushake** [marcrobledo/acnl-editor#15]
I know you've said in other threads you don't have time to work on updates right now, but at some time in the future, an option for Japanese item/villager names would be very much appreciated!

**Comment by marcrobledo** [comment]
In order to add the japanese items I'd need the Script/Str/STR_Item_name.umsbt file from the japanese game data files.

**Comment by mirukushake** [comment]
[This](https://drive.google.com/file/d/0B-Q0lpvHLkSdMkd2N3RCRy1STWs/view?usp=sharing) should be the file, correct?

**Comment by mirukushake** [comment]
Sorry, I just realized the cart doesn't have Welcome amiibo items or any other updates, so [here](https://drive.google.com/open?id=0B-Q0lpvHLkSdbElKcmtOM0NabGM) is the correct file from the updates. Let me know if you need any others.

**Comment by marcrobledo** [comment]
added to 0bfa6fd62c339be70ec28e3110de65069313ef88
