### ISSUE TITLE
import/export

### ISSUE THREAD

**Issue by AgentScarlet** [marcrobledo/acnl-editor#18]
i cant export my map and according to the stuff in the acnl editor source stuff it says i can and not only that it say si can import old garden.dat maps. buts not doing. how can i export my garden_plus.dat map now?? i dont see it anywhere

**Comment by marcrobledo** [comment]
There is no button to export data.
The import function just looks for another savegame. And it's compatible with both garden.dat and garden_plus.dat (you can't mix them though).
