### ISSUE TITLE
11.6 Problem

### ISSUE THREAD

**Issue by Mini-Craylings** [marcrobledo/acnl-editor#24]
Is there a way to make this work on 11.6? Is there something I'm missing? I wanted to help my friend out with this and I've hacked my 3DS before but after 11.6 my soundhax stopped working (they probably patched it...). Is there still a way to use this application? Please someone respond soon!

**Comment by sandhoners123** [comment]
Get an NTR cartridge and install Luma3DS

**Comment by danwdart** [comment]
I installed a save manager through FBI, would that help you?
