### ISSUE TITLE
Feature Request - Hidden values

### ISSUE THREAD

**Issue by Wolfenpilot687** [marcrobledo/acnl-editor#36]
I was wondering if there's any way to read some of the values in the game that aren't visible. For example, how many weeds a player has pulled out so far, or how many fish or bugs they have caught. This would make it a lot simpler for completionists (who don't feel like cheating a badge in) to gauge how close they are to their goal!

**Comment by Anonymous42456** [comment]
You could use NLSE to check the values

**Comment by Wolfenpilot687** [comment]
NLSE was last updated 3 years ago and is not equipped to be able to use the new garden_plus.dat files.

**Comment by Anonymous42456** [comment]
That's odd. I used it a few weeks ago with no issues. Maybe you have the pre-installed update version of ACNL.

**Comment by marcrobledo** [comment]
Indeed, the editor has access to these values. I can add some code to show them easily.

**Comment by Wolfenpilot687** [comment]
That'd be amazing! Thank you!

**Comment by Wolfenpilot687** [comment]
Oh, yeah! Silly me. Really appreciated, man!
