### ISSUE TITLE
ACNL Save Manager Cannot Find Game?

### ISSUE THREAD

**Issue by ktorres08** [marcrobledo/acnl-editor#47]
So I recently had to update my Homebrew to v2.0.0 since my console updated to version 11.9.0-42U. I installed the ACNL Save Editor to the correct folder, but when I open the ACNL Save Manager, it says "The application you attempted to run requires a title that is not installed in the system." When I try to use JK's Save Manager, it gets stuck on the yellow screen.

Any reason why this may be? The cartridge is inserted in the system.

**Comment by KevinBlue18** [comment]
Most people said to use Checkpoint instead of ACNL Save Manager since it's based on JKSM which is not updated anymore.
