### ISSUE TITLE
New PWP button

### ISSUE THREAD

**Issue by mmroos1983** [marcrobledo/acnl-editor#6]
Hi, can you please release a version where you can add buildings and/or both police stations? I know you did not because of issues that happened sometimes but can you upload it as a use at your own risk download?

If I get issues I always have a old save to get into the game again.

tl;dr, please put up pwp builder version as use at your own risk optional download.
Sorry for bad English.

**Comment by marcrobledo** [comment]
I have not much free time currently, so I'll only fix critical bugs. But I'll add the option to add new PWPs sooner or later.
For now, you can just open the web browser console (usually with F12) and type: addBuilding() and a new PWP will be added

**Comment by mmroos1983** [comment]
Thanks! Works perfectly!

**Comment by xusuu** [comment]
Another thing that would be good is the ability to not only add buildings, but bridges and stuff. Even after toying with the enable/disable in the web browser elements after putting addBuilding() into the console, it seemed I was able to place new bridges on the editor but the game didn't seem to recognize it.
![image](https://cloud.githubusercontent.com/assets/28203711/25774218/56940a14-3259-11e7-9811-58ba4bedd778.png)
![image](http://i.imgur.com/XUK1IyA.jpg)

**Comment by marcrobledo** [comment]
The game only allows you to have 3 bridges.
Before the WA update you could hack a fourth, but then the game started to glitch and act incorrectly.
The WA update added a lot of patches, and now it removes any fourth bridge.

**Comment by xusuu** [comment]
That makes sense then. 
Btw I tried to add a normal PWP (totem pole) using the addBuilding() in the web browser console. It successfully creates a new PWP in the editor but it doesn't show up in game. The totem pole is 1x1 and I gave it enough space, and still nothing appears in its spot.

**Comment by marcrobledo** [comment]
Added in 0e4885d
