### ISSUE TITLE
online editor not opening files

### ISSUE THREAD

**Issue by gardnerk** [marcrobledo/acnl-editor#62]
The website loads, but when I browse to a garden_plus.dat file and choose to open, the browse window closes and goes back to the website home (rather than opening the file to show the town map).  Encountered this problem on Saturday 4/27, worked properly again on 4/28, encountering problem again today 4/29

**Comment by marcrobledo** [comment]
I cannot replicate this bug.

Please post the garden_plus.dat file here so I can take a look.

Which website are you visiting?
http://www.marcrobledo.com/acnl-editor/
or
https://www.marcrobledo.com/acnl-editor/ ?

Which version is shown in site footer?

**Comment by gardnerk** [comment]
Well, everything is opening now.  I had last tried a little over an hour ago (at about 6am EST), and I've enclosed the file I was using.  I tried several different files though.

The issue occurred using the https site, but I don't see a footer even when printing the home screen.  I'm using Safari, and the home screen says that the editor is the 4/28 version.  Here is the first file that wouldn't open.

Thank you!
________________________________

**Comment by gardnerk** [comment]
Here - just a couple of minutes later, and now this file isn't opening.  The "browse to" dialog box opens, then when I choose the file, the dialog box closes and stays on the editor https home page.
________________________________

**Comment by marcrobledo** [comment]
You didn't post the file :-(

**Comment by gardnerk** [comment]
Sorry about that!  I had not used GitHub before, so I didn't upload the file properly.  Here is one of the files.  It won't open in the online editor on 3 different computers (one Mac, a PC with Windows 8, and a PC with Windows 10) using Safari, Chrome, or Internet Explorer.

Most of my files won't open online, but they open fine in the downloaded version of your editor.  And, if I make a new garden_plus.dat file for the same town, it opens fine.

I don't know enough about software to make any educated guesses, but my older files aren't opening online, and my newer ones are.  If no one else is having this issue, then perhaps I've edited these older towns in some way that just isn't compatible? I'm curious, but it may not be worth investigating on your end.  Thank you again!

[garden_plus.dat.zip](https://github.com/marcrobledo/acnl-editor/files/3132400/garden_plus.dat.zip)

**Comment by marcrobledo** [comment]
Thank you :-)
Found the bug, gonna fix it asap!

**Comment by marcrobledo** [comment]
Fixed!
Will upload the changes tomorrow.

If you really need to use the editor, use the old [v1.4](https://github.com/marcrobledo/acnl-editor/releases/tag/v1.4) for now.

**Comment by gardnerk** [comment]
No rush on my account - the offline version is working fine for me.  I really appreciate this though. :)

**Comment by marcrobledo** [comment]
Should be fixed in 916f432292400bb55b35d985e4eaa0c305bbe31e :-)

You might to force a cache refresh in order to get the latest editor version (make sure it's the 1st May version).
