### ISSUE TITLE
All items showing as NaNxNaN, showing as ??? in game

### ISSUE THREAD

**Issue by MSCourier** [marcrobledo/acnl-editor#64]
In the save editor, all the items that are placed in pockets and dressers/I try to place are showing as
NaNxNaN: "item"
and in game, they are the typical item leaf and named "???"

**Comment by marcrobledo** [comment]
Yes, they show up as NaNxNaN, but it's just a cosmetic issue.

However, it saves them correctly. I don't get any glitched item called ??? in-game.

**Comment by MSCourier** [comment]
Items in dressers moved to pockets now show as the item
![acnl](https://user-images.githubusercontent.com/50182339/57049203-a2ff7900-6c3c-11e9-8ba3-13e817d6650b.PNG)

**Comment by marcrobledo** [comment]
Can you post your savegames?

**Comment by marcrobledo** [comment]
The NaNxNaN thing has been fixed now (make sure you are using 2nd May version).

I'll keep this issue open since there's still something else to fix!
