### ISSUE TITLE
Trees and bushes won't transfer from editor to game

### ISSUE THREAD

**Issue by WolfofGlory** [marcrobledo/acnl-editor#69]
I used New Leaf Save Editor back in 2017 and didn't experience any issues regarding editing my town and getting all of the results I wanted into my save file. It's been roughly two years since then and I decided to re-install Homebrew after 3DS version updates and have gotten into the New Leaf Save Editor once more. After a while of using the editor I noticed something that didn't occur back in 2017 and that seemingly nobody is complaining about at the moment, and that is the fact that trees, bushes and bamboos don't grow in all of the spots in the game where I had placed them in the editor. After testing this problem out by re-adding them over and over again in the editor and trying to get them load in my game, I realised that they don't grow in places where the game doesn't want you to have them growing, for example on the beach, in the river, too close to houses or pwps or on grey ground areas around the train station, the recycle shop, the town hall and the town tree. I have no problem placing trees in these areas on the editor, but once I import the save file back into my 3DS and load the game, the trees and bushes will be completely gone as if I never placed them there to begin with.

Is this some odd bug that I'm experiencing or has the new leaf game/the editor been updated so that you can no longer place trees and bushes wherever you want? I'm not experiencing any other issues, but it certainly is disheartening that I can no longer go wild with adding whatever I want wherever I want in my town with the help of the editor. This is only an issue that persists with trees, bushes and bamboos; I can still move houses, pwps and other things around the map and put them into places where the game doesn't normally allow them. 

If there is anything I can do, I'd gladly hear from you regarding this issue, and thank you in advance. :)

**Comment by marcrobledo** [comment]
Are you playing on Welcome Amiibo update, right?
If I recall correctly, that was a fix on WA.

**Comment by WolfofGlory** [comment]
Yes I am, and that would make sense. I did play Welcome Amiibo back in 2017 too, but it could have been patched later on. Thank you for your help though!
