### ISSUE TITLE
Wrong Season/Grass

### ISSUE THREAD

**Issue by Hiddenthorn** [marcrobledo/acnl-editor#70]
I finally got around to hacking my acnl game, but when I put in my garden.dat file, it only gave me options for winter grass. (It's summer!) I think it might have something to do with the fact that as I was installing the Checkpoint app on my 3ds, it somehow reset the date to 2/2/2001. I changed the date back to present day, and saved my down to the SD card again, but it still only gives me winter grass options. Any fixes? I really want to be able to hack my game.

![Capture](https://user-images.githubusercontent.com/53279410/61831927-44edc680-ae24-11e9-9a1e-d2e8be372245.PNG)

**Comment by NuttySian** [comment]
The winter bit is just the second part. 
So for the first option it's triangle in summer, but square in winter.
