### ISSUE TITLE
Hey. please respond!

### ISSUE THREAD

**Issue by SirEnder125** [marcrobledo/acnl-editor#79]
Hello. I was wondering how you compiled your source code as a website? And is this possible in c++??? 

Thanks.

Great work on the save editor btw! (Kinda outdated and my save won't open with it.) :D

**Comment by marcrobledo** [comment]
This is Javascript, it's compiled during runtime.
You can make editors in c++. If you are asking if you can turn c++ code into a website: no, you need to port it to Javascript, or any other backend language (not recommended).

Post your savegame so I can take a look at it.

**Comment by marcrobledo** [comment]
Your savegame opens fine with the editor.

Are you using the latest version? (23th April 2020)

**Comment by SirEnder125** [comment]
Oh, Hmmm. Well I used Vapecord-Plugin, maybe that messed something up, and fixed it since, I haven't checked in a while if it worked with the editor. Thanks for checking that.

**Comment by SirEnder125** [comment]
By the way, how did you setup the website, like how could I make a webpage/.html file that others can view???
