### ISSUE TITLE
Saving grass maps

### ISSUE THREAD

**Issue by xusuu** [marcrobledo/acnl-editor#8]
Hey Marc! I'm so grateful for this project; it really eliminates the unnecessary stress of having to worry when some new meaty looking villager moves in over your hybrids. (And it allows for more town creativity).

One thing I was so happy of was the new grass map feature and it sure works, but there's one problem. After injecting an edited grass map, the next day the game gobbles it up again. I don't think this part is fixable since it must be within the game's internal data, but this issue isn't anything new, since it has always happened with the Revive grass option. However, that was easy to fix since it restored the grass at a few clicks. 
The new grass map feature is great but I only wish there were a way to save and import grass maps we'd like to keep so that we don't have to draw it again every day. It just seems a bit confusing to have to save an entire old map which has your grass pattern to import over your new one when you can simply save the grass map as its own internal thing. 
This isn't urgent since there is a way around it and I know you're busy (take your time!), but it would be much more convenient to just have the grass map on my desktop and be able to import it onto my new save. Just to avoid accidentally overriding my old map when I backup the game in Homebrew, which contained the grass map I wanted to keep (I can easily see myself doing this because of my inattentiveness and then it'll just hit me afterward like oh _SHIT_). Thanks!

**Comment by marcrobledo** [comment]
Just rename a garden.dat/garden_plus.dat file with your desired grass map to my_map.acnlmap and it will work exactly the same it worked before.
I did it this way because it was a lot easier for me, and it was also clean for end users since they only need to keep a single file for all maps.
