### ISSUE TITLE
Do you have to pay to keep this save editor up?

### ISSUE THREAD

**Issue by SirEnder125** [marcrobledo/acnl-editor#81]
Hello. I was just wondering if you have to pay to keep this save editor on the
internet? :P May be a dumb question. If so,  sorry.

**Comment by marcrobledo** [comment]
No.

**Comment by vinnyg0621** [comment]
well, it's a good thing we don't! 😉

**Comment by SirEnder125** [comment]
Lol. Dang that was really four years ago, eh? I was trying to make something cool like this to help people or maybe just make a website, I'm not even sure. I mean "No." gives all the information I needed I suppose..
