### ISSUE TITLE
Multiple PWPs in the RAM editor but not in-game?

### ISSUE THREAD

**Issue by Rocker26a** [marcrobledo/acnl-editor#9]
Basically, I've been having this weird problem recently where when I start a new PWP, Lloyd turns invisible when I leave the screen by entering a house, going to Main Street or just saving. When I go to the next day, he's gone completely whereas previously I still collided with him.

So after a seemingly random number of attempts, they began showing up as normal. But when I check my town in the Editor, it shows all the attempts I made to build them along the side.

[You can see it here.](http://i.imgur.com/GuD5qRk.png?) Any suggestions about what I can do? Can I delete them in the editor or anything? Another thing but it's less of a problem, I randomly have my 4th bridge working again, but I can't change it to anything other than Northwest by Southeast. I'd like to have it just be North to South if I can. Let me know what you think. Cheers.

**Comment by marcrobledo** [comment]
Hopefully, this has been fixed in 916f432292400bb55b35d985e4eaa0c305bbe31e
Also, you can now change bridges at your desire.

Anyway, having a 4th bridge is not recommended.
